"""Add company prep questions model

Revision ID: ccd0539c0df7
Revises: 3731ab796ef8
Create Date: 2026-03-15 12:32:12.618756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ccd0539c0df7'
down_revision: Union[str, Sequence[str], None] = '3731ab796ef8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_embeddings_vector'), table_name='embeddings', postgresql_ops={'vector': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_table('embeddings')
    op.drop_index(op.f('idx_resume_profiles_student'), table_name='resume_profiles')
    op.drop_table('resume_profiles')
    op.drop_index(op.f('idx_snapshots_drive'), table_name='drive_resume_snapshots')
    op.drop_table('drive_resume_snapshots')
    op.drop_table('job_drives')
    op.drop_table('applications')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('application_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('drive_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('student_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('snapshot_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'applied'::text"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['drive_id'], ['job_drives.drive_id'], name=op.f('applications_drive_id_fkey')),
    sa.ForeignKeyConstraint(['snapshot_id'], ['drive_resume_snapshots.snapshot_id'], name=op.f('applications_snapshot_id_fkey')),
    sa.PrimaryKeyConstraint('application_id', name=op.f('applications_pkey'))
    )
    op.create_table('job_drives',
    sa.Column('drive_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('company', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('role', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('jd_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('drive_id', name='job_drives_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('drive_resume_snapshots',
    sa.Column('snapshot_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('drive_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('student_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('resume_version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('structured_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('embedding_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('applied_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['drive_id'], ['job_drives.drive_id'], name=op.f('drive_resume_snapshots_drive_id_fkey')),
    sa.ForeignKeyConstraint(['embedding_id'], ['embeddings.embedding_id'], name=op.f('drive_resume_snapshots_embedding_id_fkey')),
    sa.PrimaryKeyConstraint('snapshot_id', name=op.f('drive_resume_snapshots_pkey'))
    )
    op.create_index(op.f('idx_snapshots_drive'), 'drive_resume_snapshots', ['drive_id'], unique=False)
    op.create_table('resume_profiles',
    sa.Column('profile_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('resume_version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('raw_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('structured_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('embedding_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['embedding_id'], ['embeddings.embedding_id'], name=op.f('resume_profiles_embedding_id_fkey')),
    sa.PrimaryKeyConstraint('profile_id', name=op.f('resume_profiles_pkey'))
    )
    op.create_index(op.f('idx_resume_profiles_student'), 'resume_profiles', ['student_id'], unique=False)
    op.create_table('embeddings',
    sa.Column('embedding_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('owner_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('model', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content_hash', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('embedding_id', name=op.f('embeddings_pkey'))
    )
    op.create_index(op.f('idx_embeddings_vector'), 'embeddings', ['vector'], unique=False, postgresql_ops={'vector': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###
